version: "3"

services: 
  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    # volumes: 
      # - .:go/src/github.com/hanami125/todo-app
      # - gomod:/go/pkg/mod
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=mysql:3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_DATABASE=todo
    depends_on: 
      - mysql
  mysql:
    image: mysql:5.7
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=todo
    ports:
      - "3306:3306"

volumes:
  gomod: {}
  mysql: {}